/**
 * Every route either runtime serves, in one of three lists. Each runner checks its own runtime
 * against them at the end of its run (shared/contract/guard.ts):
 *
 * - CONTRACT_ROUTES: both runtimes serve it, and a scenario must send it and get a 2xx answer.
 * - WORKER_ONLY and LOCAL_ONLY: one runtime serves it, with the reason the other does not. A route
 *   the Worker keeps only to answer 410 Gone counts as one it does not serve.
 *
 * A route added to either runtime fails that runtime's guard until it is placed here. A reason
 * that starts with OPEN is a question still to answer: if the app calls the route in the mode
 * that lacks it, that mode is broken there.
 */
import type { RouteKey } from './guard';

export const CONTRACT_ROUTES: readonly RouteKey[] = [
  'GET /api/accounts',
  'POST /api/accounts',
  'DELETE /api/accounts/:id',
  'GET /api/accounts/:id',
  'PUT /api/accounts/:id',
  'GET /api/accounts/:id/history',
  'POST /api/accounts/:id/history',
  'GET /api/accounts/:id/reconciliation-summary',
  'GET /api/accounts/history/timeline',
  'POST /api/accounts/recompute-balances',
  'GET /api/analytics/category-trends',
  'GET /api/analytics/daily-heatmap',
  'GET /api/analytics/distinct-years',
  'GET /api/analytics/sankey',
  'GET /api/analytics/weeks',
  'POST /api/auth/login',
  'POST /api/auth/logout',
  'GET /api/auth/me',
  'GET /api/bills',
  'POST /api/bills',
  'DELETE /api/bills/:id',
  'GET /api/bills/:id',
  'PUT /api/bills/:id',
  'POST /api/bills/:id/mark-paid',
  'GET /api/bills/calendar',
  'GET /api/bills/upcoming',
  'GET /api/budgets',
  'POST /api/budgets',
  'DELETE /api/budgets/:id',
  'PUT /api/budgets/:id',
  'PUT /api/budgets/:id/rollover',
  'GET /api/budgets/alerts',
  'POST /api/budgets/allocate',
  'POST /api/budgets/backfill-from-spending',
  'POST /api/budgets/duplicate-last',
  'GET /api/budgets/forecast',
  'POST /api/budgets/from-expenses',
  'GET /api/budgets/history',
  'GET /api/budgets/improvements',
  'GET /api/budgets/summary',
  'GET /api/budgets/zero-based',
  'GET /api/budgets/zero-based/summary',
  'POST /api/calculator/compound-interest',
  'GET /api/calculator/emergency-fund',
  'POST /api/calculator/retire',
  'DELETE /api/categories',
  'GET /api/categories',
  'POST /api/categories',
  'DELETE /api/categories/:id',
  'GET /api/categories/:id',
  'PUT /api/categories/:id',
  'POST /api/categories/apply-mappings',
  'POST /api/categories/auto-map',
  'GET /api/categories/mappings',
  'POST /api/categories/mappings',
  'DELETE /api/categories/mappings/:id',
  'DELETE /api/clear-all',
  'GET /api/counterparties',
  'GET /api/dashboard',
  'GET /api/dashboard/charts',
  'GET /api/dashboard/net-worth',
  'GET /api/dashboard/summary',
  'GET /api/export',
  'GET /api/export/:type',
  'GET /api/health',
  'GET /api/housing',
  'POST /api/housing',
  'DELETE /api/housing/:id',
  'PUT /api/housing/:id',
  'POST /api/import',
  'GET /api/import-logs',
  'POST /api/import-logs',
  'DELETE /api/import-logs/:id',
  'GET /api/import-sources',
  'POST /api/import-sources',
  'DELETE /api/import-sources/:id',
  'PUT /api/import-sources/:id',
  'POST /api/import/execute',
  'POST /api/import/googlesheet',
  'POST /api/import/upload',
  'GET /api/loans',
  'POST /api/loans',
  'DELETE /api/loans/:id',
  'GET /api/loans/:id',
  'PUT /api/loans/:id',
  'POST /api/loans/:id/calculate',
  'POST /api/loans/:id/prepayments',
  'DELETE /api/loans/:id/prepayments/:prepayId',
  'POST /api/loans/:id/rates',
  'DELETE /api/loans/:id/rates/:rateId',
  'PUT /api/loans/:id/rates/:rateId',
  'GET /api/portfolio/holdings',
  'POST /api/portfolio/holdings',
  'DELETE /api/portfolio/holdings/:id',
  'PUT /api/portfolio/holdings/:id',
  'POST /api/portfolio/prices',
  'GET /api/portfolio/summary',
  'DELETE /api/profile/data',
  'GET /api/profiles',
  'POST /api/profiles',
  'DELETE /api/profiles/:id',
  'PATCH /api/profiles/:id',
  'PUT /api/profiles/:id',
  'POST /api/profiles/reseed-demo',
  'POST /api/receipts',
  'DELETE /api/receipts/:id',
  'GET /api/receipts/:id',
  'GET /api/receipts/:id/file',
  'GET /api/receipts/file/:filename',
  'GET /api/receipts/transaction/:transactionId',
  'POST /api/receipts/upload',
  'GET /api/recurring',
  'POST /api/recurring',
  'DELETE /api/recurring/:id',
  'GET /api/recurring/:id',
  'PUT /api/recurring/:id',
  'POST /api/recurring/:id/populate',
  'GET /api/recurring/upcoming',
  'GET /api/reports/annual-pdf',
  'POST /api/reports/custom',
  'GET /api/reports/monthly-pdf',
  'GET /api/reports/pl-summary',
  'GET /api/reports/pl-summary-pdf',
  'GET /api/reports/tax-summary',
  'GET /api/reports/tax-summary-pdf',
  'GET /api/retirement-goals',
  'POST /api/retirement-goals',
  'DELETE /api/retirement-goals/:id',
  'PUT /api/retirement-goals/:id',
  'GET /api/retirement/projection',
  'GET /api/retirement/settings',
  'PUT /api/retirement/settings',
  'GET /api/savings-goals',
  'POST /api/savings-goals',
  'DELETE /api/savings-goals/:id',
  'PUT /api/savings-goals/:id',
  'POST /api/savings-goals/:id/contribute',
  'GET /api/settings',
  'PUT /api/settings',
  'POST /api/settings/set-storage',
  'GET /api/stats/monthly',
  'GET /api/storage-mode',
  'POST /api/storage-mode',
  'GET /api/tags',
  'POST /api/tags',
  'DELETE /api/tags/:id',
  'PUT /api/tags/:id',
  'POST /api/tags/:id/apply',
  'GET /api/tags/:id/summary',
  'POST /api/tags/:id/transactions',
  'GET /api/tags/rules',
  'POST /api/tags/rules',
  'DELETE /api/tags/rules/:ruleId',
  'PUT /api/tags/rules/:ruleId',
  'POST /api/tags/rules/preview',
  'GET /api/tags/summary',
  'DELETE /api/transactions',
  'GET /api/transactions',
  'POST /api/transactions',
  'DELETE /api/transactions/:id',
  'GET /api/transactions/:id',
  'PUT /api/transactions/:id',
  'PATCH /api/transactions/:id/reconcile',
  'GET /api/transactions/:id/tags',
  'POST /api/transactions/:id/tags',
  'PUT /api/transactions/:id/tags',
  'PUT /api/transactions/bulk',
  'GET /api/transactions/by-tag/:tagId',
  'PUT /api/transactions/reconcile-batch',
  'POST /api/transactions/reconcile/bulk',
  'GET /api/transactions/reconcile/summary',
  'GET /api/transactions/summary',
];

/** Contract routes no scenario sends yet. The list only shrinks: empty is the goal. */
export const UNCOVERED: readonly RouteKey[] = [
  'GET /api/analytics/category-trends',
  'GET /api/analytics/daily-heatmap',
  'GET /api/analytics/distinct-years',
  'GET /api/analytics/sankey',
  'GET /api/analytics/weeks',
  'POST /api/auth/login',
  'POST /api/auth/logout',
  'GET /api/auth/me',
  'DELETE /api/clear-all',
  'GET /api/counterparties',
  'GET /api/dashboard',
  'GET /api/dashboard/charts',
  'GET /api/dashboard/net-worth',
  'GET /api/dashboard/summary',
  'GET /api/export',
  'GET /api/export/:type',
  'GET /api/health',
  'POST /api/import',
  'GET /api/import-sources',
  'POST /api/import-sources',
  'DELETE /api/import-sources/:id',
  'PUT /api/import-sources/:id',
  'DELETE /api/profile/data',
  'GET /api/profiles',
  'POST /api/profiles',
  'DELETE /api/profiles/:id',
  'PATCH /api/profiles/:id',
  'PUT /api/profiles/:id',
  'POST /api/profiles/reseed-demo',
  'POST /api/receipts',
  'DELETE /api/receipts/:id',
  'GET /api/receipts/:id',
  'GET /api/receipts/:id/file',
  'GET /api/receipts/file/:filename',
  'GET /api/receipts/transaction/:transactionId',
  'POST /api/receipts/upload',
  'GET /api/reports/annual-pdf',
  'POST /api/reports/custom',
  'GET /api/reports/monthly-pdf',
  'GET /api/reports/pl-summary',
  'GET /api/reports/pl-summary-pdf',
  'GET /api/reports/tax-summary',
  'GET /api/reports/tax-summary-pdf',
  'GET /api/settings',
  'PUT /api/settings',
  'POST /api/settings/set-storage',
  'GET /api/stats/monthly',
  'GET /api/storage-mode',
  'POST /api/storage-mode',
];

export const WORKER_ONLY: Readonly<Record<string, string>> = {
  'DELETE /api/account': 'Deletes the cloud account itself.',
  'DELETE /api/accounts/:id/history':
    'OPEN: only the Worker serves this (accounts.ts). Does the app call it in local-first?',
  'GET /api/account/api-tokens':
    'API tokens authenticate against the Worker; local-first has no API.',
  'POST /api/account/api-tokens':
    'API tokens authenticate against the Worker; local-first has no API.',
  'DELETE /api/account/api-tokens/:id':
    'API tokens authenticate against the Worker; local-first has no API.',
  'POST /api/auth/forgot-password': 'Signing in. Local-first has no account to sign in to.',
  'GET /api/auth/google/callback': 'Signing in. Local-first has no account to sign in to.',
  'GET /api/auth/google/start': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/logout-all': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/register': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/resend-verification': 'Signing in. Local-first has no account to sign in to.',
  'GET /api/auth/reset-password': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/reset-password': 'Signing in. Local-first has no account to sign in to.',
  'GET /api/auth/sessions': 'Signing in. Local-first has no account to sign in to.',
  'DELETE /api/auth/sessions/:id': 'Signing in. Local-first has no account to sign in to.',
  'GET /api/auth/verify-email': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/import/file-sheet':
    'Retired: answers 410 Gone, telling an old cached page to upload the file again. The Import page reads a file in one upload now, and calls this in neither mode.',
  'POST /api/billing/checkout': 'Billing belongs to a cloud account.',
  'POST /api/billing/portal': 'Billing belongs to a cloud account.',
  'GET /api/billing/status': 'Billing belongs to a cloud account.',
  'POST /api/billing/webhook': 'Billing belongs to a cloud account.',
  'GET /api/bills/notifications':
    'OPEN: only the Worker serves this (bills.ts). Does the app call it in local-first?',
  'GET /api/bills/summary':
    'OPEN: only the Worker serves this (bills.ts). Does the app call it in local-first?',
  'GET /api/calculators/currency':
    'OPEN: only the Worker serves this (calculators.ts). Does the app call it in local-first?',
  'GET /api/calculators/loans':
    'OPEN: only the Worker serves this (calculators.ts). Does the app call it in local-first?',
  'GET /api/calculators/loans/amortization':
    'OPEN: only the Worker serves this (calculators.ts). Does the app call it in local-first?',
  'GET /api/calculators/mortgages':
    'OPEN: only the Worker serves this (calculators.ts). Does the app call it in local-first?',
  'GET /api/calculators/retirement':
    'OPEN: only the Worker serves this (calculators.ts). Does the app call it in local-first?',
  'GET /api/calculators/savings':
    'OPEN: only the Worker serves this (calculators.ts). Does the app call it in local-first?',
  'GET /api/calculators/units':
    'OPEN: only the Worker serves this (calculators.ts). Does the app call it in local-first?',
  'POST /api/auth/email-code/request': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/email-code/verify': 'Signing in. Local-first has no account to sign in to.',
  'GET /mcp': 'The MCP server is the Worker.',
  'POST /mcp': 'The MCP server is the Worker.',
  'GET /robots.txt': 'Served to crawlers and uptime checks, not to the app.',
  'GET /api/notifications/settings': 'Email notifications are sent by the Worker.',
  'PUT /api/notifications/settings': 'Email notifications are sent by the Worker.',
  'POST /api/notifications/test-email': 'Email notifications are sent by the Worker.',
  'POST /api/notifications/trigger': 'Email notifications are sent by the Worker.',
  'GET /api/notifications/unsubscribe': 'Email notifications are sent by the Worker.',
  'GET /api/auth/passkeys': 'Signing in. Local-first has no account to sign in to.',
  'DELETE /api/auth/passkeys/:id': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/passkeys/login/options': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/passkeys/login/verify': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/passkeys/register/options':
    'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/passkeys/register/verify':
    'Signing in. Local-first has no account to sign in to.',
  'GET /api/plans': 'Billing belongs to a cloud account.',
  'GET /api/receipts':
    'OPEN: only the Worker serves this (receipts.ts). Does the app call it in local-first?',
  'POST /api/receipts/:id/categorize':
    'OPEN: only the Worker serves this (receipts.ts). Does the app call it in local-first?',
  'POST /api/receipts/:id/export':
    'OPEN: only the Worker serves this (receipts.ts). Does the app call it in local-first?',
  'POST /api/receipts/:id/share':
    'OPEN: only the Worker serves this (receipts.ts). Does the app call it in local-first?',
  'POST /api/receipts/:id/split':
    'OPEN: only the Worker serves this (receipts.ts). Does the app call it in local-first?',
  'GET /api/reports/compare':
    'OPEN: only the Worker serves this (reports.ts). Does the app call it in local-first?',
  'DELETE /api/reports/custom/:id':
    'OPEN: only the Worker serves this (reports.ts). Does the app call it in local-first?',
  'GET /api/reports/custom/:id':
    'OPEN: only the Worker serves this (reports.ts). Does the app call it in local-first?',
  'PUT /api/reports/custom/:id':
    'OPEN: only the Worker serves this (reports.ts). Does the app call it in local-first?',
  'GET /api/reports/overview':
    'OPEN: only the Worker serves this (reports.ts). Does the app call it in local-first?',
  'POST /api/reports/save':
    'OPEN: only the Worker serves this (reports.ts). Does the app call it in local-first?',
  'GET /api/reports/saved':
    'OPEN: only the Worker serves this (reports.ts). Does the app call it in local-first?',
  'POST /api/support/contact': 'Support messages are sent by the Worker.',
  'GET /api/tags/:id':
    'OPEN: only the Worker serves this (tags.ts). Does the app call it in local-first?',
  'POST /api/auth/2fa/disable': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/2fa/enable': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/2fa/setup': 'Signing in. Local-first has no account to sign in to.',
  'GET /api/auth/2fa/status': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/auth/2fa/verify': 'Signing in. Local-first has no account to sign in to.',
  'POST /api/v1/import': 'The public v1 API is the Worker.',
  'GET /api/v1/snapshot': 'The public v1 API is the Worker.',
};

/** Keyed by method and the local router's pattern source, as `routes` in localApiRouter.ts has it. */
export const LOCAL_ONLY: Readonly<Record<string, string>> = {
  'GET ^\\/app-info$': 'OPEN: only local-first serves this. Does the app call it when signed in?',
  'GET ^\\/auth\\/check$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'GET ^\\/profiles\\/(\\d+)$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'GET ^\\/analytics$': 'OPEN: only local-first serves this. Does the app call it when signed in?',
  'GET ^\\/transactions\\/export$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'DELETE ^\\/accounts\\/(\\d+)\\/history\\/(\\d+)$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'GET ^\\/budgets\\/(\\d+)$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'GET ^\\/savings-goals\\/(\\d+)$':
    'A single goal read, for api.getGoal, which nothing in the app calls: the Goals page reads the list, in both modes.',
  'GET ^\\/loans\\/(\\d+)\\/rate-periods$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'PUT ^\\/loans\\/(\\d+)\\/rate$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'GET ^\\/loans\\/(\\d+)\\/rates$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'POST ^\\/loans\\/(\\d+)\\/prepayment$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'GET ^\\/loans\\/(\\d+)\\/prepayments$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'POST ^\\/categories\\/seed$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'GET ^\\/tags\\/(\\d+)\\/transactions$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'POST ^\\/import\\/preview$':
    'A bulk import of { items }, which nothing in the app sends: the Import page previews with POST /api/import/execute and dry_run, in both modes.',
  'POST ^\\/import\\/file-sheet$':
    'The old pick-a-sheet step after an upload, which the Import page calls in neither mode; the Worker answers it 410 Gone.',
  'GET ^\\/exchange-rates$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'GET ^\\/exchange-rates\\/([A-Z]{3})\\/([A-Z]{3})$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'POST ^\\/retirement$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
  'GET ^\\/housing\\/(\\d+)$':
    'A single housing expense, for no caller: the Housing page reads the list, in both modes.',
  'POST ^\\/housing\\/calculate$':
    'The housing affordability calculator, for api.calculateHousing, which nothing in the app calls.',
  'GET ^\\/logs$': 'OPEN: only local-first serves this. Does the app call it when signed in?',
  'POST ^\\/logs$': 'OPEN: only local-first serves this. Does the app call it when signed in?',
  'POST ^\\/logs\\/clear$':
    'OPEN: only local-first serves this. Does the app call it when signed in?',
};
