blank_issues_enabled: true
contact_links:
  - name: Contributing Guidelines
    url: https://github.com/Komediruzecki/finance-manager/blob/main/CONTRIBUTING.md
    about: Please read our contributing guidelines before opening a PR
  - name: Roadmap
    url: https://github.com/Komediruzecki/finance-manager/blob/main/ROADMAP.md
    about: Check the roadmap for planned features
