var window=(()=>{var l={currentId:parseInt(localStorage.getItem("currentProfileId")||"1"),selectedIds:[],async loadProfiles(){let e=await api("/profiles");return Array.isArray(e)?e:[]},async switchTo(e){this.currentId=e,this.selectedIds=[e],localStorage.setItem("currentProfileId",e),localStorage.setItem("selectedProfileIds",JSON.stringify([e])),await this.refreshUI(),this.updateDropdownDisplay();let t=window.location.hash.slice(1)||"dashboard";this.navigateToPage(t)},async toggleProfile(e){let t=this.selectedIds.indexOf(e);t>=0?this.selectedIds.splice(t,1):this.selectedIds.push(e),this.selectedIds.length===0&&(this.selectedIds=[this.currentId]),localStorage.setItem("selectedProfileIds",JSON.stringify(this.selectedIds)),this.updateDropdownDisplay(),this.renderDropdown(),this.navigateToPage(window.location.hash.slice(1)||"dashboard")},async selectAllProfiles(){let e=await this.loadProfiles();this.selectedIds=e.map(t=>t.id),localStorage.setItem("selectedProfileIds",JSON.stringify(this.selectedIds)),this.updateDropdownDisplay(),this.renderDropdown(),this.navigateToPage(window.location.hash.slice(1)||"dashboard")},async clearMultiSelect(){this.selectedIds=[this.currentId],localStorage.setItem("selectedProfileIds",JSON.stringify(this.selectedIds)),this.updateDropdownDisplay(),this.renderDropdown(),this.navigateToPage(window.location.hash.slice(1)||"dashboard")},navigateToPage(e){e==="dashboard"?dashboard.load():e==="transactions"?transactions.load():e==="budgets"?budgets.load():e==="loans"?loans.load():e==="categories"?categories.load():e==="settings"?settings.load():e==="accounts"?accounts.load():e==="analytics"&&analytics.load()},toggleDropdown(){let e=document.getElementById("profile-menu");e.classList.toggle("open"),e.classList.contains("open")&&this.renderDropdown()},async renderDropdown(){let e=await this.loadProfiles(),t=document.getElementById("profile-menu"),s=auth.isLoggedIn(),i=`
      <div class="profile-dropdown-header">
        <span>${this.selectedIds.length>1?"Household View":"Select Profile"}</span>
        ${this.selectedIds.length>1?'<button class="profile-dropdown-clear" onclick="profile.clearMultiSelect()">Clear</button>':'<button class="profile-dropdown-all" onclick="profile.selectAllProfiles()">All</button>'}
      </div>
    `;i+=e.map(o=>`
      <div class="profile-dropdown-item${this.selectedIds.includes(o.id)?" active":""}"
           onclick="profile.toggleProfile(${o.id})">
        <span class="profile-checkbox">${this.selectedIds.includes(o.id)?"&#10003;":""}</span>
        <span>${this.escapeHtml(o.name)}</span>
        ${o.id!==1?`<button class="delete-profile-btn" onclick="event.stopPropagation(); profile.confirmDelete(${o.id}, '${this.escapeHtml(o.name).replace(/'/g,"\\'")}')">&#10005;</button>`:""}
      </div>
    `).join(""),s&&(i+=`<div class="profile-dropdown-divider"></div>
      <div class="profile-dropdown-add" onclick="modal.open('profile-modal'); profile.toggleDropdown()">
        <svg width="14" height="14" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>
        New Profile
      </div>`),t.innerHTML=i,t.classList.add("open");let a=o=>{t.parentElement.contains(o.target)||(t.classList.remove("open"),document.removeEventListener("click",a))};setTimeout(()=>document.addEventListener("click",a),0)},updateDropdownDisplay(){let e=document.getElementById("profile-btn-name");this.selectedIds.length>1?(e.textContent=`${this.selectedIds.length} Profiles`,e.style.fontWeight="600"):this.selectedIds.length===1&&this.loadProfiles().then(t=>{let s=t.find(n=>n.id===this.selectedIds[0]);s&&(e.textContent=s.name),e.style.fontWeight=""})},async refreshUI(){let e=document.getElementById("profile-btn-name"),s=(await this.loadProfiles()).find(n=>n.id===this.currentId);e&&(e.textContent=s?s.name:"Profile")},getProfileIds(){return this.selectedIds.length>0?this.selectedIds:[this.currentId]},async createProfile(){let e=document.getElementById("profile-name-input").value.trim();if(!e)return toast("Enter a profile name","error");let t=await api("/profiles",{method:"POST",body:{name:e}});t.error?toast(t.error,"error"):(await this.switchTo(t.id),modal.close("profile-modal"),toast("Profile created","success"))},confirmDelete(e,t){confirm(`Delete profile "${t}"? This cannot be undone.`)&&api(`/profiles/${e}`,{method:"DELETE"}).then(()=>{this.currentId===e?this.switchTo(1):(this.selectedIds=this.selectedIds.filter(s=>s!==e),this.refreshUI(),this.updateDropdownDisplay()),toast("Profile deleted","success")})},async init(){try{let e=localStorage.getItem("selectedProfileIds");e?this.selectedIds=JSON.parse(e):this.selectedIds=[this.currentId]}catch{this.selectedIds=[this.currentId]}document.addEventListener("click",e=>{let t=document.getElementById("profile-menu"),s=document.getElementById("profile-btn");!t.contains(e.target)&&!s.contains(e.target)&&t.classList.remove("open")}),await this.refreshUI(),this.updateDropdownDisplay()},escapeHtml(e){let t=document.createElement("div");return t.textContent=e,t.innerHTML}};})();
