/**
 * The downloadable sample CSV offered on the File Upload tab — one month of
 * realistic rows covering every column the importer maps, so a user can see the
 * exact expected shape (and re-import the file as a test).
 */

const TEMPLATE_HEADER = [
  'Date',
  'Description',
  'Amount',
  'Category',
  'Currency',
  'Beneficiary',
  'Payor',
  'Means of Payment',
  'Exchange Rate',
  'Notes',
  'Type',
  'Amount Local',
]

const TEMPLATE_ROWS: string[][] = [
  [
    '2024-01-01',
    'Salary January',
    '3200.00',
    'Salary',
    'EUR',
    'Employer Inc.',
    'Employer Inc.',
    'Bank Transfer',
    '1.0',
    'Monthly salary',
    'income',
    '3200.00',
  ],
  [
    '2024-01-02',
    'Rent Payment',
    '-950.00',
    'Rent',
    'EUR',
    'Landlord Ltd.',
    'John Doe',
    'Bank Transfer',
    '1.0',
    'January rent',
    'expense',
    '-950.00',
  ],
  [
    '2024-01-03',
    'Grocery Store',
    '-78.35',
    'Groceries',
    'EUR',
    'Supermarket',
    'John Doe',
    'Debit Card',
    '1.0',
    'Weekly groceries',
    'expense',
    '-78.35',
  ],
  [
    '2024-01-04',
    'Electric Bill',
    '-112.50',
    'Utilities',
    'EUR',
    'Power Co.',
    'John Doe',
    'Direct Debit',
    '1.0',
    'January electricity',
    'expense',
    '-112.50',
  ],
  [
    '2024-01-05',
    'Gas Station',
    '-55.00',
    'Transport',
    'EUR',
    'Fuel Station',
    'John Doe',
    'Credit Card',
    '1.0',
    'Fuel for car',
    'expense',
    '-55.00',
  ],
  [
    '2024-01-06',
    'Internet Bill',
    '-39.99',
    'Utilities',
    'EUR',
    'ISP Provider',
    'John Doe',
    'Direct Debit',
    '1.0',
    'Monthly internet',
    'expense',
    '-39.99',
  ],
  [
    '2024-01-07',
    'Restaurant Dinner',
    '-62.40',
    'Dining',
    'EUR',
    'Bella Italia',
    'John Doe',
    'Credit Card',
    '1.0',
    'Dinner with friends',
    'expense',
    '-62.40',
  ],
  [
    '2024-01-08',
    'Gym Membership',
    '-45.00',
    'Health',
    'EUR',
    'FitLife Gym',
    'John Doe',
    'Direct Debit',
    '1.0',
    'Monthly gym fee',
    'expense',
    '-45.00',
  ],
  [
    '2024-01-10',
    'Freelance Work',
    '450.00',
    'Freelance',
    'EUR',
    'Client XYZ',
    'Client XYZ',
    'Bank Transfer',
    '1.0',
    'Website project',
    'income',
    '450.00',
  ],
  [
    '2024-01-12',
    'Phone Bill',
    '-29.99',
    'Utilities',
    'EUR',
    'Telecom Co.',
    'John Doe',
    'Direct Debit',
    '1.0',
    'Monthly phone plan',
    'expense',
    '-29.99',
  ],
  [
    '2024-01-14',
    'Pharmacy',
    '-23.50',
    'Health',
    'EUR',
    'City Pharmacy',
    'John Doe',
    'Debit Card',
    '1.0',
    'Vitamins and supplies',
    'expense',
    '-23.50',
  ],
  [
    '2024-01-15',
    'Cinema Tickets',
    '-28.00',
    'Entertainment',
    'EUR',
    'CineMax',
    'John Doe',
    'Credit Card',
    '1.0',
    'Movie night',
    'expense',
    '-28.00',
  ],
  [
    '2024-01-17',
    'Transfer to Savings',
    '-500.00',
    'Savings',
    'EUR',
    'My Savings Account',
    'John Doe',
    'Bank Transfer',
    '1.0',
    'Monthly savings',
    'expense',
    '-500.00',
  ],
  [
    '2024-01-18',
    'Grocery Store',
    '-85.20',
    'Groceries',
    'EUR',
    'Supermarket',
    'John Doe',
    'Debit Card',
    '1.0',
    'Weekly groceries',
    'expense',
    '-85.20',
  ],
  [
    '2024-01-20',
    'Clothing Purchase',
    '-120.00',
    'Shopping',
    'EUR',
    'Fashion Store',
    'John Doe',
    'Credit Card',
    '1.0',
    'Winter jacket',
    'expense',
    '-120.00',
  ],
  [
    '2024-01-22',
    'Car Insurance',
    '-185.00',
    'Insurance',
    'EUR',
    'AutoInsure Ltd.',
    'John Doe',
    'Bank Transfer',
    '1.0',
    'Quarterly payment',
    'expense',
    '-185.00',
  ],
  [
    '2024-01-24',
    'Grocery Store',
    '-72.10',
    'Groceries',
    'EUR',
    'Supermarket',
    'John Doe',
    'Debit Card',
    '1.0',
    'Weekly groceries',
    'expense',
    '-72.10',
  ],
  [
    '2024-01-25',
    'Online Course',
    '-49.99',
    'Education',
    'EUR',
    'EduPlatform',
    'John Doe',
    'Credit Card',
    '1.0',
    'Programming course',
    'expense',
    '-49.99',
  ],
  [
    '2024-01-27',
    'Haircut',
    '-30.00',
    'Personal Care',
    'EUR',
    'Barber Shop',
    'John Doe',
    'Debit Card',
    '1.0',
    'Monthly haircut',
    'expense',
    '-30.00',
  ],
  [
    '2024-01-29',
    'Restaurant Lunch',
    '-18.50',
    'Dining',
    'EUR',
    'Cafe Central',
    'John Doe',
    'Debit Card',
    '1.0',
    'Lunch break',
    'expense',
    '-18.50',
  ],
  [
    '2024-01-31',
    'Grocery Store',
    '-68.75',
    'Groceries',
    'EUR',
    'Supermarket',
    'John Doe',
    'Debit Card',
    '1.0',
    'Weekly groceries',
    'expense',
    '-68.75',
  ],
  [
    '2024-02-01',
    'Salary February',
    '3200.00',
    'Salary',
    'EUR',
    'Employer Inc.',
    'Employer Inc.',
    'Bank Transfer',
    '1.0',
    'Monthly salary',
    'income',
    '3200.00',
  ],
]

export function downloadSampleTemplate() {
  const csv = [TEMPLATE_HEADER, ...TEMPLATE_ROWS].map((r) => r.join(',')).join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'finance_import_template.csv'
  a.click()
  URL.revokeObjectURL(url)
}
